//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.DetailCommandes = new HashSet<DetailCommande>();
        }
    
        public int ART_Id { get; set; }
        public int ART_SCAT_Id { get; set; }
        public string ART_Libelle { get; set; }
        public string ART_Description { get; set; }
        public decimal ART_Prix { get; set; }
        public int ART_Stock { get; set; }
        public string ART_Image { get; set; }
    
        public virtual SousCategorie SousCategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailCommande> DetailCommandes { get; set; }
    }
}
