//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.DetailCommandes = new HashSet<DetailCommande>();
        }
    
        public int COM_Id { get; set; }
        public int COM_CLI_Id { get; set; }
        public System.DateTime COM_Date { get; set; }
        public string COM_Statut { get; set; }
        public System.DateTime COM_DateLivraison { get; set; }
        public string COM_Nom { get; set; }
        public string COM_Prenom { get; set; }
        public string COM_Civilite { get; set; }
        public string COM_Adresse { get; set; }
        public string COM_CodePostal { get; set; }
        public string COM_Ville { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailCommande> DetailCommandes { get; set; }
    }
}
